AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Metrics/LineLength:
  Max: 500
Metrics/BlockLength:
  Max: 300
Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 50
